services:
  mc:
    image: itzg/minecraft-server:java25@sha256:b42d19bcda4673fedf1ae14a94e729708275c00777be95d5a6e27c11847f7d64
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      SEED: "7830518263619659759"
      VERSION: "1.21.10"
      MEMORY: "2048M"
      MAX_PLAYERS: "4"
      MOTD: ${MOTD}
      ICON: ${ICON}
      USE_AIKAR_FLAGS: "true"
      USE_MEOWICE_FLAGS: "true"
      TZ: "Europe/Berlin"
      DIFFICULTY: "2"
      SIMULATION_DISTANCE: "24"
      VIEW_DISTANCE: "24"
      LEVEL: ${LEVEL}
      ENABLE_WHITELIST: "true"
      WHITELIST: ${WHITELIST}
      OPS: ${OPS}
    volumes:
      - "data:/data"
volumes:
  data:
