services:
  mc:
    image: itzg/minecraft-server:java25@sha256:9faa6aefeedd5a883c3ee241653fd1421529bdbafc428d0513e43cae0f2b7d68
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      SEED: "7830518263619659759"
      VERSION: "26.2"
      MEMORY: "2048M"
      MAX_PLAYERS: "4"
      MOTD: ${MOTD}
      ICON: ${ICON}
      USE_AIKAR_FLAGS: "true"
      USE_MEOWICE_FLAGS: "true"
      TZ: "Europe/Berlin"
      DIFFICULTY: "2"
      SIMULATION_DISTANCE: "24"
      VIEW_DISTANCE: "24"
      LEVEL: ${LEVEL}
      ENABLE_WHITELIST: "true"
      WHITELIST: ${WHITELIST}
      OPS: ${OPS}
    volumes:
      - "data:/data"
volumes:
  data:
