services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    container_name: palworld-server
    restart: unless-stopped
    stop_grace_period: 30s
    ports:
      - "${PORT:?Set PORT in Portainer}:${PORT:?Set PORT in Portainer}/udp"
      - "${QUERY_PORT:?Set QUERY_PORT in Portainer}:${QUERY_PORT:?Set QUERY_PORT in Portainer}/udp"
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: ${TZ:?Set TZ in Portainer}
      PORT: ${PORT:?Set PORT in Portainer}
      QUERY_PORT: ${QUERY_PORT:?Set QUERY_PORT in Portainer}
      PLAYERS: ${PLAYERS:?Set PLAYERS in Portainer}
      SERVER_PASSWORD: ${SERVER_PASSWORD:?Set SERVER_PASSWORD in Portainer}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:?Set ADMIN_PASSWORD in Portainer}
      SERVER_NAME: ${SERVER_NAME:?Set SERVER_NAME in Portainer}
      SERVER_DESCRIPTION: ${SERVER_DESCRIPTION:?Set SERVER_DESCRIPTION in Portainer}
      COMMUNITY: ${COMMUNITY:?Set COMMUNITY in Portainer}
      CROSSPLAY_PLATFORMS: ${CROSSPLAY_PLATFORMS:?Set CROSSPLAY_PLATFORMS in Portainer}
      REST_API_ENABLED: ${REST_API_ENABLED:?Set REST_API_ENABLED in Portainer}
      REST_API_PORT: ${REST_API_PORT:?Set REST_API_PORT in Portainer}
    volumes:
      - palworld_data:/palworld

volumes:
  palworld_data:
