services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    container_name: palworld-server
    restart: unless-stopped
    stop_grace_period: 30s
    ports:
      - "8211:8211/udp"
      - "27015:27015/udp"
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/Berlin"
      PORT: "8211"
      QUERY_PORT: "27015"
      PLAYERS: "16"
      SERVER_PASSWORD: ${SERVER_PASSWORD:?Set SERVER_PASSWORD in Portainer}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:?Set ADMIN_PASSWORD in Portainer}
      SERVER_NAME: "Schinken Pizza"
      SERVER_DESCRIPTION: "Pals, Pizza und fragwürdige Arbeitsbedingungen - Schinken inklusive."
      COMMUNITY: "true"
      CROSSPLAY_PLATFORMS: "(Steam,Xbox,PS5,Mac)"
      REST_API_ENABLED: "true"
      REST_API_PORT: "8212"
    volumes:
      - palworld_data:/palworld

volumes:
  palworld_data:
