services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest@sha256:cc84f2f5eb3c7734353701ccbaa24ed02dacb0d119114e50e4251e2005f3990a
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}
    ports:
      - 3000:3000
    volumes:
      - homepage_config:/app/config
    restart: unless-stopped
volumes:
  homepage_config:
