services:
  homepage:
    image: gethomepage/homepage:v1.13.2@sha256:a0b71c8e757298d02560186bab9fbe3fc2d375c523a62cc1019177b37e48aa28
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}
    ports:
      - 3000:3000
    volumes:
      - homepage_config:/app/config
    restart: unless-stopped
volumes:
  homepage_config:
