services:
  app:
    image: jc21/nginx-proxy-manager:2.15.0@sha256:83b8d6a2d5ddfdd1f9f8ee240499953dec5f7bbf3b4dafc5f4ac394f1edca930
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      TZ: "Europe/Berlin"
      DB_POSTGRES_HOST: 'db'
      DB_POSTGRES_PORT: '5432'
      DB_POSTGRES_USER: 'npm'
      DB_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_POSTGRES_NAME: 'npm'
      DISABLE_IPV6: 'true'
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: postgres:17.10@sha256:0027bef26712baaee437a4ea48fdf3d2d2e2bc5f0d81615374408ca320f3c7e3
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'npm'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: 'npm'
    volumes:
      - postgresql:/var/lib/postgresql/data
volumes:
  data:
  letsencrypt:
  postgresql:
